name: media_asset_example
description: Example app for the media_asset package.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  media_asset:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
